typography_spectrum: 0.8340770078357309
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5623941402882338
  lightness: 0.17865126975812018
  saturation: 0.21246348950080574
  rhythmicContrast: 0.7638854840770364
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.630376297980547
analytics:
  google: null
  facebook: null
  twitter: null
name: Kaila Colbin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
